- type: job
  id: StationEngineer
  name: job-name-engineer
  description: job-description-engineer
  playTimeTracker: JobStationEngineer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 7200
  startingGear: StationEngineerGear
  icon: "StationEngineer"
  supervisors: job-supervisors-ce
  antagAdvantage: 3 # The classic ideal traitor role
  access:
  - Maintenance
  - Engineering
  - External
  extendedAccess:
  - Atmospherics

- type: startingGear
  id: StationEngineerGear
  equipment:
    # head: ClothingHeadHatHardhatYellow
    jumpsuit: ClothingUniformJumpsuitEngineering
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBootsWork
    # outerClothing: ClothingOuterVestHazard
    id: EngineerPDA
    # eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityFilled
    ears: ClothingHeadsetEngineering
  innerclothingskirt: ClothingUniformJumpskirtEngineering
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
