- type: department
  id: Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  - SAI
  - CentralCommandOfficial
  - ChiefServiceSupervisor
  - ChiefEngineer
  - ChiefMedicalOfficer
  - ERTEngineer
  - ERTJanitor
  - ERTLeader
  - ERTMedical
  - ERTSecurity
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Mystagogue

- type: department
  id: Service
  description: department-Civilian-description
  color: "#9FED58"
  roles:
  - Bartender
  - Botanist
  - Boxer
  - Chef
  - Clown
  - Gladiator
  - ChiefServiceSupervisor
  - Janitor
  - Lawyer
  - Librarian
  - MailCarrier
  - MedicalIntern
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Zookeeper
  - ServiceWorker
  - TechnicalAssistant
  - Quartermaster

- type: department
  id: Engineering
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - StationEngineer
  - SalvageTechnician

- type: department
  id: Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - MedicalCyborg
  - Paramedic

- type: department
  id: Security
  description: department-Security-description
  color: "#DE3A3A"
  roles:
  - HeadOfSecurity
  - PrisonGuard
  - SecurityCadet
  - SecurityOfficer
  - Detective
  - Warden
  - Prisoner

- type: department
  id: Epistemics
  description: department-Epistemics-description
  color: "#D381C9"
  roles:
  - Mystagogue
  - ForensicMantis
  - Epistemologist
  - Chaplain
  - Cataloguer

- type: department
  id: Silicon
  description: department-Silicon-description
  color: "#8D9AAC"
  roles:
  - SAI
  - Cyborg
  - MedicalCyborg
