- type: job
  id: SAI
  name: "station AI"
  playTimeTracker: SAI
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 60000
  icon: "SAI"
  supervisors: "all crew"
  accessGroup:
    - AllAccess
  canBeAntag: false
  jobEntity: AI
  startingGear: CyborgGear # for char preview only

- type: startingGear
  id: AIGear
  equipment:
    id: AIPDA
