- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  startingGear: LawyerGear
  icon: "Lawyer"
  antagAdvantage: 2 #Starting sec access and radio
  supervisors: job-supervisors-css
  access:
  - Service
  - Brig

- type: startingGear
  id: LawyerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack  # TODO change jumpsuit to randomiser of the 4 variants
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetSecurity
  inhand:
    right hand: BriefcaseBrownFilled
    left hand: HyperlinkBookSpaceLaw
  innerclothingskirt: ClothingUniformJumpskirtLawyerBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
