- type: startingGear
  id: OldstationCrewScientistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitScientist
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLab
    id: SciencePDA
  innerclothingskirt: ClothingUniformJumpskirtScientist
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled

- type: startingGear
  id: OldstationCrewEngineerGear
  equipment:
    head: ClothingHeadHatHardhatYellow
    jumpsuit: ClothingUniformJumpsuitEngineering
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBootsWork
    outerClothing: ClothingOuterVestHazard
    id: EngineerPDA
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityFilled
  innerclothingskirt: ClothingUniformJumpskirtEngineering
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled

- type: startingGear
  id: OldstationCrewSecurityGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetHelmetOld
    outerClothing: ClothingOuterVestKevlar
    id: SecurityPDA
    belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpskirtSec
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
